version: "3"
services:
    influx:
        image: influxdb:1.7.10-alpine
        ports:
            - 8086:8086
    grafana:
        image: grafana/grafana:7.0.1
        ports:
            - 3000:3000
